
version: "2"

services:
  sonarqube:
    image: sonarqube:8.4.1-community
    restart: always
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonarqube
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
#    volumes:
#      - /srv/docker/sonarqube/sonarqube_conf:/opt/sonarqube/conf
#      - /srv/docker/sonarqube/sonarqube_data:/opt/sonarqube/data
#      - /srv/docker/sonarqube/sonarqube_extensions:/opt/sonarqube/extensions
#      - /srv/docker/sonarqube/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"

  db:
    image: postgres
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonarqube
    volumes:
      - /srv/docker/sonarqube/postgresql:/var/lib/postgresql
      - /srv/docker/sonarqube/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
